---
name: Build kobo-ssh

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: build-kobo-ssh
  cancel-in-progress: false

jobs:
  filter-changes:
    name: Filter changes
    runs-on: ubuntu-latest
    outputs:
      build_changed: ${{ steps.build-files-changed.outputs.any_changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build files changed
        id: build-files-changed
        uses: tj-actions/changed-files@2f7c5bfce28377bc069a65ba478de0a74aa0ca32 # v46
        with:
          files: |
            .github/workflows/build.yaml
            KoboRoot/**
            Dockerfile

  build-koboroot:
    if: ${{ needs.filter-changes.outputs.build_changed == 'true' }}
    name: Build KoboRoot
    runs-on: ubuntu-latest
    needs:
      - filter-changes
    permissions:
      contents: write
    env:
      TOOLCHAIN_IMAGE: kobo-ssh-toolchain:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        id: build
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
          DOCKER_BUILD_SUMMARY: false
        with:
          push: false
          load: true
          tags: ${{ env.TOOLCHAIN_IMAGE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Fetch build output
        uses: kohlerdominik/docker-run-action@v2.0.0
        with:
          image: ${{ env.TOOLCHAIN_IMAGE }}
          volumes: |
            ${{ github.workspace }}/dist:/dist
          run: |
            cp /output/KoboRoot.tgz /dist/

      - name: Release artifact
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "2025.87"
          body: |
            Dropbear 2025.87 for Kobo eReaders
          files: dist/KoboRoot.tgz
