---
name: Build kobo-ssh

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: build-kobo-ssh
  cancel-in-progress: false

jobs:
  filter-changes:
    name: Filter changes
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.changed-files.outputs.changed_files }}
    steps:
      - name: Build files changed
        id: build-files-changed
        uses: bjw-s-labs/action-changed-files@b1144fc772fca235a50902c7bb6cc431cc7d8e27 # v0.3.2
        with:
          patterns: |
            .github/workflows/build.yaml
            KoboRoot/**
            Dockerfile

  build-koboroot:
    if: ${{ needs.filter-changes.outputs.changed-files != '[]' }}
    name: Build KoboRoot
    runs-on: ubuntu-latest
    needs:
      - filter-changes
    permissions:
      contents: write
    env:
      TOOLCHAIN_IMAGE: kobo-ssh-toolchain:latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Build image
        uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v6.16.0
        id: build
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
          DOCKER_BUILD_SUMMARY: false
        with:
          push: false
          load: true
          tags: ${{ env.TOOLCHAIN_IMAGE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Fetch build output
        uses: kohlerdominik/docker-run-action@170cd7d34e33265bfba818cddf461bae2d6c44d2 # v2.0.0
        with:
          image: ${{ env.TOOLCHAIN_IMAGE }}
          volumes: |
            ${{ github.workspace }}/dist:/dist
          run: |
            cp /output/KoboRoot.tgz /dist/

      - name: Release artifact
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2.2.2
        with:
          tag_name: "2025.87"
          body: |
            Dropbear 2025.87 for Kobo eReaders
          files: dist/KoboRoot.tgz
